import React, { useCallback, useEffect, useState } from "react";

const API_BASE_URL =
  process.env.REACT_APP_API_BASE_URL || "http://localhost:8080";

function formatNumber(value) {
  return Number(value || 0).toLocaleString();
}

function formatCost(value) {
  return Number(value || 0).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 6,
    maximumFractionDigits: 8
  });
}

function formatDate(value) {
  if (!value) {
    return "—";
  }

  return new Date(value).toLocaleString();
}

function CostDashboard({ active }) {
  const [dashboard, setDashboard] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const loadDashboard = useCallback(async () => {
    setLoading(true);
    setError("");

    try {
      const response = await fetch(
        `${API_BASE_URL}/api/gbrain/cost/summary`
      );

      if (!response.ok) {
        throw new Error(
          `Cost API returned HTTP ${response.status}`
        );
      }

      const data = await response.json();
      setDashboard(data);
    } catch (requestError) {
      setError(
        requestError.message ||
          "Unable to load cost-dashboard information."
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (active) {
      loadDashboard();
    }
  }, [active, loadDashboard]);

  if (!dashboard && loading) {
    return (
      <div className="kb-dashboard-message">
        Loading cost information...
      </div>
    );
  }

  if (!dashboard && error) {
    return (
      <div className="kb-dashboard-message kb-dashboard-message--error">
        <p>{error}</p>

        <button type="button" onClick={loadDashboard}>
          Try Again
        </button>
      </div>
    );
  }

  const data = dashboard || {
    totalRequests: 0,
    totalInputTokens: 0,
    totalOutputTokens: 0,
    totalTokens: 0,
    estimatedCostUsd: 0,
    modelBreakdown: {},
    recentRequests: []
  };

  const modelRows = Object.entries(data.modelBreakdown || {});

  return (
    <div className="kb-cost-dashboard">
      <div className="kb-cost-dashboard__heading">
        <div>
          <span className="kb-eyebrow">
            AI USAGE AND COST
          </span>

          <h1>Cost Dashboard</h1>

          <p>
            Monitor LLM requests, token consumption, and estimated
            OpenRouter cost.
          </p>
        </div>

        <button
          type="button"
          className="kb-refresh-button"
          onClick={loadDashboard}
          disabled={loading}
        >
          {loading ? "Refreshing..." : "Refresh"}
        </button>
      </div>

      {error && (
        <div className="kb-inline-error">
          The previous information is shown, but refresh failed:
          {" "}
          {error}
        </div>
      )}

      <div className="kb-metric-grid">
        <MetricCard
          label="LLM Requests"
          value={formatNumber(data.totalRequests)}
          helper="Answer-generation requests"
        />

        <MetricCard
          label="Input Tokens"
          value={formatNumber(data.totalInputTokens)}
          helper="Tokens sent to the model"
        />

        <MetricCard
          label="Output Tokens"
          value={formatNumber(data.totalOutputTokens)}
          helper="Tokens generated by the model"
        />

        <MetricCard
          label="Total Tokens"
          value={formatNumber(data.totalTokens)}
          helper="Input and output combined"
        />

        <MetricCard
          label="Estimated Cost"
          value={formatCost(data.estimatedCostUsd)}
          helper="Based on configured pricing"
          highlighted
        />
      </div>

      <section className="kb-dashboard-panel">
        <div className="kb-dashboard-panel__header">
          <div>
            <h2>Usage by Model</h2>
            <p>Estimated usage grouped by the selected model.</p>
          </div>
        </div>

        {modelRows.length === 0 ? (
          <EmptyState message="No model usage has been recorded yet. Submit a question from the Q&A Workspace." />
        ) : (
          <div className="kb-table-wrapper">
            <table className="kb-dashboard-table">
              <thead>
                <tr>
                  <th>Model</th>
                  <th>Requests</th>
                  <th>Input Tokens</th>
                  <th>Output Tokens</th>
                  <th>Total Tokens</th>
                  <th>Estimated Cost</th>
                </tr>
              </thead>

              <tbody>
                {modelRows.map(([model, summary]) => (
                  <tr key={model}>
                    <td className="kb-model-name">{model}</td>
                    <td>{formatNumber(summary.requests)}</td>
                    <td>{formatNumber(summary.inputTokens)}</td>
                    <td>{formatNumber(summary.outputTokens)}</td>
                    <td>{formatNumber(summary.totalTokens)}</td>
                    <td>{formatCost(summary.estimatedCostUsd)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      <section className="kb-dashboard-panel">
        <div className="kb-dashboard-panel__header">
          <div>
            <h2>Recent Requests</h2>
            <p>Most recent requests recorded by the Java API.</p>
          </div>
        </div>

        {!data.recentRequests?.length ? (
          <EmptyState message="No requests have been recorded during this application session." />
        ) : (
          <div className="kb-table-wrapper">
            <table className="kb-dashboard-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Operation</th>
                  <th>Model</th>
                  <th>Input</th>
                  <th>Output</th>
                  <th>Cost</th>
                </tr>
              </thead>

              <tbody>
                {data.recentRequests.map((request) => (
                  <tr key={request.id}>
                    <td>{formatDate(request.timestamp)}</td>
                    <td>{request.operation}</td>
                    <td className="kb-model-name">
                      {request.model}
                    </td>
                    <td>{formatNumber(request.inputTokens)}</td>
                    <td>{formatNumber(request.outputTokens)}</td>
                    <td>{formatCost(request.estimatedCostUsd)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      <p className="kb-cost-disclaimer">
        Cost values are estimates based on the pricing configured in
        the Spring Boot application. Current MVP data resets when the
        API restarts.
      </p>
    </div>
  );
}

function MetricCard({ label, value, helper, highlighted = false }) {
  return (
    <article
      className={`kb-metric-card ${
        highlighted ? "kb-metric-card--highlighted" : ""
      }`}
    >
      <span>{label}</span>
      <strong>{value}</strong>
      <small>{helper}</small>
    </article>
  );
}

function EmptyState({ message }) {
  return (
    <div className="kb-dashboard-empty">
      {message}
    </div>
  );
}

export default CostDashboard;